"""Expiry alerts generated by the scheduler and the audit log."""
from __future__ import annotations

from datetime import date, datetime

from sqlalchemy import Date, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base
from app.models.enums import AlertChannel, AlertStatus
from app.models.mixins import TimestampMixin
from app.models.types import EnumStr


class Alert(Base, TimestampMixin):
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(primary_key=True)
    user_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True)
    vehicle_id: Mapped[int | None] = mapped_column(
        ForeignKey("vehicles.id", ondelete="CASCADE"), index=True, nullable=True
    )
    document_id: Mapped[int | None] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), nullable=True
    )

    title: Mapped[str] = mapped_column(String(200), nullable=False)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    due_date: Mapped[date | None] = mapped_column(Date, index=True, nullable=True)
    lead_days: Mapped[int | None] = mapped_column(Integer, nullable=True)

    channel: Mapped[AlertChannel] = mapped_column(
        EnumStr(AlertChannel), default=AlertChannel.in_app, nullable=False
    )
    status: Mapped[AlertStatus] = mapped_column(
        EnumStr(AlertStatus), default=AlertStatus.pending, index=True, nullable=False
    )
    # De-dupe key so we don't re-create the same alert on every sweep.
    dedupe_key: Mapped[str | None] = mapped_column(String(200), index=True, nullable=True)
    sent_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    relate_vehicle = relationship("Vehicle")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Alert {self.id} {self.status} {self.title!r}>"


class AuditLog(Base, TimestampMixin):
    __tablename__ = "audit_logs"

    id: Mapped[int] = mapped_column(primary_key=True)
    actor_id: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    family_id: Mapped[int | None] = mapped_column(
        ForeignKey("families.id", ondelete="SET NULL"), index=True, nullable=True
    )
    action: Mapped[str] = mapped_column(String(80), nullable=False)
    entity_type: Mapped[str | None] = mapped_column(String(40), nullable=True)
    entity_id: Mapped[int | None] = mapped_column(Integer, nullable=True)
    detail: Mapped[str | None] = mapped_column(Text, nullable=True)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<AuditLog {self.id} {self.action}>"
